### ISSUE TITLE
Remove stains of subset

### ISSUE THREAD

**Issue by melonora** [melonora/napari-cell-gater#2]
We might want to have a filter button which provides a text field to users to fill in a regex or substring based on which stains should be filtered out. This way we give the user flexibility and reduces hardcoded parts.

**Comment by josenimo** [comment]
I think 95% of the time DAPI and DNA should do the trick. But I agree, I like reducing the hardcoded variables. 

Do you think it could be possible to create an Advance Options toggle menu? 
For these kind of 5% use cases? If it is too complicated, then we can leave it as it is right now.

**Comment by melonora** [comment]
hmm we could have it as the default value that is automatically filled.

**Comment by josenimo** [comment]
Thought about this today, 
DAPI and DNA are good defaults, I will rephrase to be more biologist friendly
